riseq:
    init_pose: [-0.1649, 0.0299, 0.1939, 0.0, 0.0, 0.0, -1.0]
    mass: 1.720
    gravity: 9.81
    thrust_coeff: 32.9  #1.3176 
    torque_coeff: 0.669 #0.028
    max_rotor_speed: 1.0  #ms
    rotor_count : 4
    true_state_publish_rate: 200
    controller_state_input: 'true_state'
    controller_type: 'euler_angle_controller'
    trajectory_wait: 2
    high_level_control_wait_time: 1
    Ixx: 0.02972 
    Iyy: 0.03072
    Izz: 0.05738
    arm_length: 0.275
    arm_vector: [0.199, 0.199, 0.0372]
    environment: 'embedded_computer'



