riseq:
    init_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
    mass: 1.
    gravity: 9.81
    thrust_coeff: 1.91e-6
    torque_coeff: 2.6e-7
    max_rotor_speed: 2200.0
    rotor_count : 4
    true_state_publish_rate: 200
    trajectory_update_rate: 200
    controller_state_input: 'fg_true_state'
    controller_type: 'euler_angle_controller'
    trajectory_wait: 0
    high_level_control_wait_time: 0
    Ixx: 0.0049 
    Iyy: 0.0049
    Izz: 0.0069
    arm_length: 0.08
    arm_vector: [0.199, 0.199, 0.0372]
    environment: 'simulator'



