riseq:
    init_pose: [0, 0, 0.0, 0.0, 0.0, 0.0, 1.0]
    mass: 1.0    #1.0kg for PX4, 1.5kg real
    gravity: 9.81
    thrust_coeff: 8.54858e-06  
    torque_coeff: 0.016 #0.028
    max_rotor_speed: 838  #rpm
    rotor_count : 4
    true_state_publish_rate: 100
    trajectory_update_rate: 100
    controller_state_input: 'fg_true_state'
    controller_type: 'euler_angle_controller'
    trajectory_wait: 5
    high_level_control_wait_time: 0
    Ixx: 1.0 #0.03 #0.0347563
    Iyy: 1.0 #0.03 # 0.0458929
    Izz: 1.0 #0.06 #0.0977
    arm_length: 0.21   
    arm_vector: [0.13, 0.22, 0.023]
    environment: 'simulator'
    challenge_name: 'easy'
    monocular_cv: 'ladder'