riseq:
    init_pose: [0, 0, 0.0, 0.0, 0.0, 0.0, 1.0]
    mass: 1.0
    gravity: 9.81
    thrust_coeff: 9.9865e-06  #1.3176 
    torque_coeff: 0.016 #0.028
    max_rotor_speed: 2200  #rpm
    rotor_count : 4
    true_state_publish_rate: 100
    trajectory_update_rate: 200
    controller_state_input: 'fg_true_state'
    controller_type: 'euler_angle_controller'
    trajectory_wait: 5
    high_level_control_wait_time: 0
    Ixx: 0.01
    Iyy: 0.01
    Izz: 0.02
    arm_length: 0.21   
    arm_vector: [0.199, 0.199, 0.0372]
    environment: 'simulator'
    challenge_name: 'easy'


