gates:
    gate_vertical: [5,-1,2]
    gate_horizontal: [-5,1,2]
    drone_init: [0,-1,0]
    detection_thresholds: [15,5,5]
perception:
    colors: 'rgb'
    cutoff: 0.001
    camera: left_rect
    theta: 30  # degree
drone:
    hover_height: 1.5 #m

environment: "simulator"  # real

#gates:
#    gate_vertical:
#        up: [, , 2.6]
#        down: [, , 1.2]
#    gate_horizontal:
#        left [, , 1.7]
#        right: [, , 1.7]
#    drone_init: [, , ]
#    detection_thresholds: [, , ]
