gates:
    drone_init: [0,-1,0]
    detection_thresholds: [15,5,5]
perception:
    colors: 'rgb'
    cutoff: 0.001
    camera: left_rect
    theta: 30  # degree
    gate_detection_wait_time: 1.0
drone:
    hover_height: 1.5 #m
    position_error_threshold: 0.2 # error threshold for position command
    one_block: 1.4
    two_block: 2.0
    drone_camera_offset_vector: [0.17,0,0]
    gate_correction_offset: [1.0,0,0]
    advance_distance: 5

environment: "simulator"  # real

gates:
    gate_vertical:
        up: [6, 0.0, 2.7]
        down: [6, 0.0, 2.7]
    gate_horizontal:
        left: [-4, 0.0, 2]
        right: [-4, 1.4, 2]
#    drone_init: [, , ]
#    detection_thresholds: [, , ]
#    at_first: 0
