gates:
    drone_init: [0,-1,0]
    detection_thresholds: [15,5,5]
perception:
    colors: 'rgb'
    cutoff: 0.001
    camera: left_rect
    theta: 30  # degree
    gate_detection_wait_time: 1.0
drone:
    hover_height: 1.5 #m
    position_error_threshold: 0.2 # error threshold for position command
    one_block: 1.4
    two_block: 1.5
    drone_camera_offset_vector: [0.17,0,0]
    gate_correction_offset: [0.5,0,0]
    advance_distance: -1
    auto_arm_offboard: true
    goal_wait_time: 5.0

environment: "simulator"  # real

gates:
    gate_vertical:
        up: [3.66, -0.1, 1.9]
        down: [3.66, -0.1, 1.9]
    gate_horizontal:
        right: [-1.63, 1.20, 1.7]
        left: [-1.63, -0.2, 1.7]
#    drone_init: [, , ]
#    detection_thresholds: [, , ]
#    at_first: 0
